### ISSUE TITLE
Pdf not always generated properly. Garbage in firefox and chrome

### ISSUE THREAD

**Issue by twinni** [kartik-v/yii2-mpdf#10]
Tried to use this extension. Generating a pdf file with destination 'D' works fine. But with destination 'I' the output is not always a pdf document but some kind of garbage with lots of non displayable charaters. 
Only windows explorer has no problem to show the generated output as a pfd document.

The strange thing is that it works sometimes correct. As an example:
Using a DetailView::widget,  which includes all fields from the model, works fine. But commenting out some of the fields the garbage will be produced. Commenting out other fields makes no trouble. 
I could't find out any rule for this behaviour.

Just an idea: You're using the beta version 6 of mpdf. Could this be the source of trouble? 

Can you please let me know how to use the actual version of mpdf with this extension?

**Comment by kartik-v** [comment]
I think its some problem to do with invalid HTML for parsing by the library.

You can try with the older versions of the mpdf by searching for mpdf repo on google/github. But it will not probably work with `yii2-mpdf`- you may need to use it directly as a PHP class.

**Comment by twinni** [comment]
@kartik-v, the problem was looking strange as the HTML produced by the DetailView::widget should be the the same for all columns. So I run some other tests and figured out that the problem has to do with the ***number of HTML tags*** used in the document. As you can see in this little snippet the error occurs while the content is < 100 (or < 66 when you activate the second variant).
I assume that mPDF (beta version) uses an pre-filled array containing stuff which can not be handled by some browsers.

Again, it might be a good idea to combine your extension with the current version of mPDF.

```php
public function actionDemo($id = 1)
    {
        for ($i = 1; $i <= $id; $i++) {
            $content .= "<p>Simple content number $i.</p>";       // fails while $id < 100
//          $content .= "<p>Simple content <strong>number $i</strong>.</p>";   // fails while $id < 66
        }
        $pdf = new Pdf([
            'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
               'content' => $content,
            'options' => [
                'title' => 'Privacy Policy - Krajee.com',
                'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
            ],
            'methods' => [
                'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);
        return $pdf->render();
    } 
```

**Comment by kartik-v** [comment]
There are reasons why the mpDF v6.0 beta has been chosen for some features not supported earlier. 

The packagist already has a repo for the mpDF older (stable) release. You may directly install that and check/test your use cases.

**Comment by twinni** [comment]
@kartik-v, packagist has the latest stable version 5.7.4.
Version 6 is only available as beta. The stable version 6 - released in december 2014 - is only available from the mpdf site (as zip file).
The beta version is one year old and might have much more bugs.

Any hints how to combine the actual version 6 with your extension?

**Comment by kartik-v** [comment]
Not clear if I am understanding you.

The extension already includes mPDF v6.0 (check kartik-v/mpdf - its an extract of v6.0 which is used by yii2-mpdf).

I thought you wanted the stable version - you can pick that directly from packagist separately.

**Comment by kartik-v** [comment]
Not clear if I am understanding you.

The extension already includes mPDF v6.0 (check [kartik-v/mpdf](https://github.com/kartik-v/mpdf/) - this repo is maintained by me on packagist and its an extract of v6.0 which is used by this extension `yii2-mpdf`).

I thought you wanted the stable version - you can pick that directly from packagist separately.

**Comment by twinni** [comment]
@kartik-v, mpdf currently offers two stable versions (5.7.4 and 6.0). Unfortunately the stable version 6 is still not available at packagist but only as an zip file. The zip download has no composer functionality like what you've added with "kartik-v/mpdf".

I don't know exactly which version is installed via "kartik-v/mpdf". If you compare the changelock files in /vendor/kartik-v/mpdf folder with file of the zip download you'll see different dates and also an extended list of new features. That's why I assume that kartik-v/mpdf installs an older (beta?) version of mpdf.

I know that this is not your fault. It's the way mpdf is released. 

I really like the way you managed the usage of mpdf and want to use your extension. But not a the risk of using a buggy (old, not stable) mpdf version.

**Comment by kartik-v** [comment]
You may check the releases at the [mpdf website](http://www.mpdf1.com/mpdf/index.php) - the stable release is v5.7.4.

v6.0 of mpdf is in beta - they keep updating the zip... note there is no github repo for v6.0 - so I had created a repo out of the v6.0 zip at a point in time. I may try to update the repo periodically when I get time (its a manual process). 

However note that if you are keen to use a stable release of mpdf, you need to use the latest stable release which is v5.7.4 (you can find it on packagist).

**Comment by kartik-v** [comment]
You may check the releases at the [mpdf website](http://www.mpdf1.com/mpdf/index.php) - the latest stable release is v5.7.4.

v6.0 of mpdf is in beta - they maybe updating the zip probably BUT note there is no github repo for v6.0 - so I had created a repo out of the v6.0 zip at a point in time in Dec 2014 (not sure if they have updated after that). I may try to update the repo periodically when I get time (its a manual process). 

However note that if you are keen to use a stable release of mpdf, you need to use the latest stable release which is v5.7.4 (you can find it on packagist).

**Comment by kartik-v** [comment]
Ok I upgraded kartik-v/mpdf to the latest version of the mPDF v6.0 beta zip file.

**Comment by twinni** [comment]
@kartik-v, thank's for upgrading to the latest mpdf version.

Unfortunately the reported issue has not been solved. Would like to report it to mpdf but this needs membership. I've asked for but havn't got it yet.

**Comment by twinni** [comment]
@kartik-v, I've to come back to this issue as it looks like that the problem occurs only while using the 'widget' like usage of this extension.
When using yii-mpdf directly or the api functions then everything works well.

The controller below includes 3 different actions to print a simple 'hello' (based on the given examples). Only the actionReport() creates a messy output.

```php
<?php

namespace frontend\controllers;

use yii\web\Controller;
use mPDF;
use kartik\mpdf\Pdf;

class X2Controller extends Controller
{

    public function actionBasic()
    {
        $pdf = new mPDF();
        $pdf->WriteHTML('Hello Kartik from basic action');
        $pdf->output();
    }

    public function actionReport()
    {
        // get your HTML raw content without any layouts or scripts
        $content = 'Hello Kartik from report action';

        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
            // call mPDF methods on the fly
            'methods' => [
                'SetHeader' => ['Krajee Report Header'],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        // return the pdf output as per the destination setting
        return $pdf->render();
    }

    public function actionAdvanced()
    {
        $content = 'Hello Kartik from advanced action';
        $pdf = new Pdf();
        $mpdf = $pdf->api; // fetches mpdf api
        $mpdf->SetHeader('Kartik Header'); // call methods or set any properties
        $mpdf->WriteHtml($content); // call mpdf write html
        echo $mpdf->Output('filename', 'I'); // call the mpdf api output as needed 
    }
}
```

**Comment by kartik-v** [comment]
The `actionReport` includes a lot of mPDF settings which the other two methods do not have... match the same properties for all three methods and then compare. Basically to isolate the problem you must add mPDF properties one by one and find out which property (mode, css, etc. is causing the problem).

**Comment by kartik-v** [comment]
The `actionReport` includes various other mPDF settings which the other two methods do not have... match the same properties for all three methods and then compare. Basically to isolate the problem you must add mPDF properties one by one and find out which property (mode, cssFile, etc.) is causing the problem.

**Comment by kartik-v** [comment]
I have a feeling that your size of the file with CSS could be causing conflict or memory overheads. The cssFile you add will allow bootstrap styling easily -- but if you are looping and adding it multiple times in the same file the size of the file will bloat...

**Comment by twinni** [comment]
@kartik-v, I used the in the actionReport just those mPDF settings out of your examples to avoid questions like 'you should have done ...'.

Anyway,  I run some additional tests and figured out that the setting of
**'mode' => Pdf::MODE_CORE***
causes the problem.

Very interesting is the fact, that the problem occurs only when content is small.
Please see the modified example below. When $max is set to something < 100 the program creates garbage. As soon as $max is 100 > greater it works fine. 
So there is obviously no problem with css files or with any (file) size limits. 

```php
public function actionReport()
    {
        $max = 100;
        for ($i = 1; $i <= $max; $i++) {
            $content .= "<p>Simple content number $i.</p>";   // works when $max is >= 100 but fails when it is < 100
        }
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE,
            // A4 paper format
            'format' => Pdf::FORMAT_A4,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting 
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}',
            // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
            // call mPDF methods on the fly
            'methods' => [
                'SetHeader' => ['Krajee Report Header'],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        // return the pdf output as per the destination setting
        return $pdf->render();
    }
```

**Comment by kartik-v** [comment]
`Pdf::MODE_CORE` will attempt to render using core inbuilt fonts - and will not render special characters (e.g. unicode) etc. in your PDF output. The advantage is smaller size of PDF - but if your content contains special characters it will face problems. You need to use `Pdf::MODE_UTF8` in that case.

Going back to my point again -- you may need to check if that's the case where you have characters in your HTML markup which is causing the PDF conversion issues with the mpdf settings you have.

Let me know if you hit anything else.

**Comment by kartik-v** [comment]
I just tested with the code you had and it works well for all scenarios (10, 20, 30 ,50, 100 or more iterations) -- that is if you remove Pdf::MODE_CORE. In this it works well using the default PDF reader fonts. As you said with Pdf::MODE_CORE --- it works well for larger content. Somehow it has issues for lesser content around 50 records or so.

Somehow it seems the core fonts available with the mpdf install could be causing the problem.

**Comment by kartik-v** [comment]
I just tested with the code you had. As you said with Pdf::MODE_CORE --- it works well for larger content. Somehow it has issues for lesser content around 50 records or so. Using Pdf::MODE_CORE uses inbuilt core fonts of your PDF reader.
The default mPDF setting is to leave it blank ... so you can try that for your use cases.

Check [the manual](http://mpdf1.com/manual/index.php?tid=184) for details on this and [details of the embedded fonts](http://mpdf1.com/manual/index.php?tid=329) to be used for UTF-8 etc.

**Comment by kartik-v** [comment]
I just tested with the code you had. As you said with Pdf::MODE_CORE --- it works well for larger content. Somehow it has issues for lesser content around 50 records or so. Using Pdf::MODE_CORE uses inbuilt core fonts of your PDF reader and gives the advantage of having a LEAN small PDF.

The default mPDF setting is to leave it blank ... so you can try that for your use cases (it maybe embedding fonts if needed for PDF to be properly rendered).

Check [the manual](http://mpdf1.com/manual/index.php?tid=184) for details on this and [details of the embedded fonts](http://mpdf1.com/manual/index.php?tid=329) to be used for UTF-8 etc.

**Comment by husanusmonov** [comment]
%PDF-1.4 %���� 3 0 obj <> /Contents 4 0 R>> endobj 4 0 obj <> stream x��R=O�0��+n�ŵ_⏬HS�H���i������y�W�R�21�I.����`-�R��Z	U?4�I�$��c-},��&�䎠�4�)_�6 ���b��4V{~7�� x_%�_�����:1|Midv��v( Ѓo��L,O��t��/���j^���{���b�(�k�%"��v�l�44bi��C$1 oƐt�W(��O؂��G��?���|������W>�Ċ3!�>Db&1�4L���o]���Z:͎�񏕙��H���Ƶ���!# ӎ�0@��M�E�����Sc�\ZL��vo�B��m�ꐻ&B�T�w\G3��<%M����|{����Φs���o��ر endstream endobj 1 0 obj <> endobj 5 0 obj <> endobj 6 0 obj <> endobj 7 0 obj <> endobj 8 0 obj <> endobj 9 0 obj <> endobj 2 0 obj <> /ExtGState << /GS1 5 0 R >> >> endobj 10 0 obj << /Producer (��mPDF 6.0) /Title (��Krajee Report Title) /CreationDate (20160705131329+01'00') /ModDate (20160705131329+01'00') >> endobj 11 0 obj << /Type /Catalog /Pages 1 0 R /OpenAction [3 0 R /XYZ null null 1] /PageLayout /OneColumn >> endobj xref 0 12 0000000000 65535 f 0000000641 00000 n 0000001194 00000 n 0000000015 00000 n 0000000223 00000 n 0000000730 00000 n 0000000791 00000 n 0000000889 00000 n 0000000985 00000 n 0000001086 00000 n 0000001340 00000 n 0000001514 00000 n trailer << /Size 12 /Root 11 0 R /Info 10 0 R /ID [<3148fd941a83be892d451cf0e9d8c39e> <3148fd941a83be892d451cf0e9d8c39e>] >> startxref 1624 %%EOF

**Comment by sheetal4123** [comment]
@kartik-v 
how to generate report in different languages
