### ISSUE TITLE
When ist the new release scheduled? 

### ISSUE THREAD

**Issue by WeeSee** [kartik-v/yii2-mpdf#105]
The last release was Version 1.0.5 made on Oct 13, 2018.

There have been many commits since then on master branch and I want to stay on an official release rather than on the "dev-master" in my composer.

When is the next release coming? 

ps: great extension!

**Comment by kartik-v** [comment]
Hi will check and update. Thanks.

**Comment by adamwinn** [comment]
1.0.6 needs to be made because of #103

**Comment by vadim-bulochnik** [comment]
Agree :) Would be good to have new release to not have "dev-master" in composer :)

**Comment by kartik-v** [comment]
Will create a new release shortly with enhancement for MPDF 8.0

**Comment by kartik-v** [comment]
New v1.0.6 released via [latest commit](https://github.com/kartik-v/yii2-mpdf/commit/7ea3a5f9bcf5bcf6d681bd82cbe843c356d1428c).
