### ISSUE TITLE
composer update

### ISSUE THREAD

**Issue by Djagannath** [kartik-v/yii2-mpdf#108]
- Updating kartik-v/yii2-mpdf dev-master (e513d17 => 7ea3a5f):     Update failed (Failed to execute git show-ref --head -d 'atal: Reference has invalid format: 'refs/remotes/origin/master

**Comment by kartik-v** [comment]
Not sure can reproduce - looks like your composer install is not corrupt or your vendor repo folder is not edited manually by you - one way to check is to rename your vendor folder and reinstall via `composer install --prefer-dist` from start
