### ISSUE TITLE
PHP Fatal Error 'yii\base\ErrorException' with message 'Undefined class constant 'self::DEST_INLINE'' 

### ISSUE THREAD

**Issue by chriswilson007** [kartik-v/yii2-mpdf#11]
In vendor/kartik-v/yii2-mpdf/Pdf.php line 281, it reads
public function output($content = '', $file = '', $dest = self::DEST_INLINE)

results in error **self::DEST_INLINE is not defined.**

Recommend changing line 281 to be
**public function output($content = '', $file = '', $dest = self::DEST_BROWSER)**

**Comment by kartik-v** [comment]
You have an outdated version of the extension .

You need to download the latest version of the package which has various enhancements and bug fixes.

**Comment by chriswilson007** [comment]
Ahhh right thanks for that,

I followed the instructions here 
http://www.yiiframework.com/extension/yii2-mpdf/#hh2

I added "kartik-v/yii2-mpdf": "*" to my composer.json file and thought 
that it would pull down the latest version.

Cheers



On 23/02/2015 16:43, Kartik Visweswaran wrote:
>
> You have an outdated version of the extension .
>
> You need to download the latest version of the package which has 
> various enhancements and bug fixes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/yii2-mpdf/issues/11#issuecomment-75579673>.
>

-- 
Chris Wilson
Web Developer



<http://www.helloevery1.com/services/> 
<http://www.helloevery1.com/news/every1-news/10-04-2012/every1-rar-award-winners> 
	


Direct: 0330 313 1243 <tel:01254855105>   | Main Line: 0844 755 0350 
<tel:01254855100>
Head Office: Chain Caul Way, Preston Lancs, PR2 2TL
Web: www.helloevery1.com <http://www.helloevery1.com/>   | FTP: Please 
contact us and we will supply login details

Registered Office: Chain Caul Way, Preston Lancs, PR2 2TL

NOTE: This email and any information contained within or attached in a 
separate file is confidential and intended solely for the Individual to 
whom it is addressed. The information or data included is solely for the 
purpose indicated or previously agreed. Any information or data included 
with this e-mail remains the property of every1 and the recipient will 
refrain from utilising the information for any purpose other than that 
indicated and upon request will destroy the information and remove it 
from their records. Any views or opinions presented are solely those of 
the author and do not necessarily represent those of every1.

If you are not the intended recipient, be advised that you have received 
this email in error and that any use, dissemination, forwarding, 
printing, or copying of this email is strictly prohibited. No warranties 
or assurances are made in relation to the safety and content of this 
e-mail and any attachments. No liability is accepted for any 
consequences arising from it. every1 reserves the right to monitor all 
e-mail communications through its internal and external networks. If you 
have received this email in error please notify our IT helpdesk on 08447 
550 350 <tel:08447550350>
