### ISSUE TITLE
Mpdf installing issue

### ISSUE THREAD

**Issue by faizanktk** [kartik-v/yii2-mpdf#114]
When i add this **"kartik-v/yii2-mpdf": "dev-master"**  to composer. Its give me  this Error

Running command composer install --no-dev
261Installing dependencies from lock file
262Verifying lock file contents can be installed on current platform.
263Your lock file does not contain a compatible set of packages. Please run composer update.
264
265  Problem 1
266    - kartik-v/yii2-widget-select2 is locked to version dev-master and an update of this package was not requested.
267    - kartik-v/yii2-widget-select2 dev-master requires select2/select2 >=4.0 -> found select2/select2[dev-master] but it does not match the constraint.
268  Problem 2
269    - kartik-v/yii2-widget-select2 dev-master requires select2/select2 >=4.0 -> found select2/select2[dev-master] but it does not match the constraint.
270    - kartik-v/yii2-widget-select2 2.2.x-dev is an alias of kartik-v/yii2-widget-select2 dev-master and thus requires it to be installed too.
271    - kartik-v/yii2-widget-select2 is locked to version 2.2.x-dev and an update of this package was not requested.
272
273Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
274
275[Container] 2020/12/24 11:20:17 Command did not exit successfully composer install --no-dev exit status 2
276[Container] 2020/12/24 11:20:17 Phase complete: PRE_BUILD State: FAILED
277[Container] 2020/12/24 11:20:17 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: composer install --no-dev. Reason: exit status 2

Why this Error come?
Thanks

**Comment by faizanktk** [comment]
@kartik-v

**Comment by m00nh3ck** [comment]
Have you tried to remove composer.lock and just use this ?

       "mpdf/mpdf": "*",
        "kartik-v/yii2-mpdf": "*"
