### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-mpdf#118]
Your requirements could not be resolved to an installable set of packages.                
  Problem 1
    - mpdf/mpdf v7.1.6 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.23) does not satisfy that requirement.
    - mpdf/mpdf v7.1.6 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.23) does not satisfy that requirement.
    - mpdf/mpdf v7.1.6 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.23) does not satisfy that requirement.
    - Installation request for mpdf/mpdf (locked at v7.1.6) -> satisfiable by mpdf/mpdf[v7.1.6].

**Comment by kartik-v** [comment]
This is actually a dependency issue at your end on the third party [mpdf](https://github.com/mpdf/mpdf) library - it seems you are trying to install `mpdf/mpdf` which is of a older release v7.x -- while the latest release is v8.x
