### ISSUE TITLE
image not show

### ISSUE THREAD

**Issue by vitatheresia** [kartik-v/yii2-mpdf#124]
![var](https://user-images.githubusercontent.com/102018480/169244994-6cf2fd88-8b26-43f2-9acc-d79c8e40b24a.JPG)

**Pilihan Tema** 
  <?php foreach ($list_tema as $item_tema) { ?>
      <img src="<?= Url::to('/web/uploads/tema_gambar/').$item_tema->tem_gambar;?>" width="100" height="80"><br>
         <?php var_dump($item_tema->tem_gambar);?>
          <?= $item_tema->tem_nama; ?>
   <?php } ?>

**Comment by RafikiSmurfJr7** [comment]
@vitatheresia did you find a solution?

**Comment by kartik-v** [comment]
This is a mPDF library need and you may want to cross check MPDF documentation. You may need the image conversion extension i.e. PHP GD extension or similar to embed images - [check this post on SFO](https://stackoverflow.com/questions/22092683/mpdf-5-7-1-image-displays-as-a-broken-x)
