### ISSUE TITLE
mPDF + amCharts\Highcharts

### ISSUE THREAD

**Issue by andreCatita** [kartik-v/yii2-mpdf#15]
Hello @kartik-v ,

Good job on this extension, I have a requirement for help, the JavaScript is the problem..

The other day I logged into a private platform, and it was running PHP, I have no clue what Framework whatsoever, whht I do know is that it was generating PDF reports on the fly, with HighCharts graphs as images in the PDF.

Now, I myself use amCharts, but even looking at Highcharts, I have no clue, how can this be made.
Is this remotely possible? Am I missing something? Even if it's not a pretty solution.. How would one?

amCharts generate grpahs as images, yes, but he needs to render the page first to run the JavaScript, so how can one export a JS graph as an image, to a PDF? In the controller?

Thanks for your input.

**Comment by kartik-v** [comment]
High charts has its own export module to convert to PDF/Image etc.
