### ISSUE TITLE
print checkboxes

### ISSUE THREAD

**Issue by elecdev2** [kartik-v/yii2-mpdf#16]
Hi,
Can someone help me please, i'm trying to print a pdf with checkboxes but its not working, only the labels are shown in the document.
PD: sorry for my poor english

**Comment by selimachour** [comment]
Hi,
Having the same problem ... any hope for a solution ?

**Comment by kartik-v** [comment]
You may need to read mpdf library docs and ensure how the html and CSS can be tweaked for PDF rendering.
