### ISSUE TITLE
Include all css files of my main layout.

### ISSUE THREAD

**Issue by nunomaduro** [kartik-v/yii2-mpdf#18]
Hey,

What should I do to include all my css files of my main layout in my pdf ?

Thank you.

**Comment by mahsa92** [comment]
Hiii 
I have the same question . What is the solution ?

**Comment by linslin** [comment]
You are able to include one CSS file by using the `cssFile` file option. Merge you css files into one, set your merged file in your `cssFile` option and you are fine.

**Comment by kartik-v** [comment]
Yes as @linslin mentioned... read [the documentation](http://demos.krajee.com/mpdf).

You can in addition to `cssFile` also set the `cssInline` to set inline CSS to be parsed in the HTML after the CSS File.
