### ISSUE TITLE
Bootstrap classes ignored

### ISSUE THREAD

**Issue by a2dgroup** [kartik-v/yii2-mpdf#25]
Hi, thank you for your great work!

I'm trying to generate a pdf from a model, formatting the html with bootstrap 3 classes but the system seems to completely ignore them. 
Here is my rendered view:

```
<div class="fattura-view container">
        <div class="row">
            <div class="col-lg-6">
                <h3>Fattura N. <?= $model->anno;?>/<?= $model->id_anno;?> del <?= $model->data_emissione;?></h3>
                <p>
                    Pagamento: <?= $model->termini_pagamento;?> Data scadenza: <?= $model->data_scadenza;?>
                    UBI Banca Popolare di Bergamo fil. Loreto (BG)<br />
                    IBAN: IT97G0542811109000000000983 - SWIFT: BEPOIT21
                </p>
            </div>
            
            
            <div class="col-lg-6">
                <h3><?= $model->cliente->ragione_sociale?></h3>
                <p>
                    <?= $model->indirizzo;?> - <?= $model->cap;?> - <?= $model->citta;?> - <?= $model->provincia;?><br />
                    P.iva:<?= $model->partita_iva;?> / Codice Fiscale: <?= $model->codice_fiscale;?>
                </p>
            </div>
        </div>

</div>
```

and here is my action in controller

```
public function actionStampaFattura($id) {
    // get your HTML raw content without any layouts or scripts
        
    $model = Fattura::findOne($id);
        
    $content = $this->renderPartial('view', array('model'=>$model));

    // setup kartik\mpdf\Pdf component
    $pdf = new Pdf([
        // set to use core fonts only
        'mode' => Pdf::MODE_CORE, 
        // A4 paper format
        'format' => Pdf::FORMAT_A4, 
        // portrait orientation
        'orientation' => Pdf::ORIENT_PORTRAIT, 
        // stream to browser inline
        'destination' => Pdf::DEST_BROWSER, 
        // your html content input
        'content' => $content,  
        // format content from your own css file if needed or use the
        // enhanced bootstrap css built by Krajee for mPDF formatting 
        'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
        // any css to be embedded if required
        'cssInline' => '.kv-heading-1{font-size:18px}', 
         // set mPDF properties on the fly
        'options' => ['title' => 'Krajee Report Title'],
         // call mPDF methods on the fly
        'methods' => [ 
            'SetHeader'=>['Krajee Report Header'], 
            'SetFooter'=>['{PAGENO}'],
        ]
    ]);

    // return the pdf output as per the destination setting
    return $pdf->render(); 
}
```

Thank you

Alessandro

**Comment by atricfox** [comment]
I met the same problem.Bootstrap V3 would be unavailable in this widget.

**Comment by tigrasti** [comment]
same here

**Comment by kartik-v** [comment]
Read mPDF library documentation - CSS Support for CSS-3 is not included - and you need to understand that. For the benefit of all - I have included with this extension a toned down Bootstrap CSS file `kv-mpdf-bootstrap.min.css` that eliminates CSS-3 specs and includes downgraded CSS specs. You need to program your code accordingly.

**Comment by jgalley** [comment]
I'm having trouble with the kartik-v Bootstrap file too. A test using @a2dgroup's code produces the same result for me. I'm seeing incorrect floating of `<div class="col-md-6"></div>` - or rather no floating, as if the page is rending in `xs` viewport width and all `col-*` classes are set at 100% width.

While I understand that mPDF doesn't support some [CSS3](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS3) specs, the included bootstrap file does include all the relevant `col-{viewport}-{width}` classes which are set to `float:left`, so I would expect the floating behaviour to work.

Could you please provide some additional documentation, perhaps examples as to what kinds of floated layouts are possible using Bootstrap `col-*` classes?

**Comment by kartik-v** [comment]
You need to check [CSS Supported by mPDF in the mPDF Library documentation](https://mpdf.github.io/css-stylesheets/supported-css.html).
