### ISSUE TITLE
Cannot open PDF in Chrome mobile

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-mpdf#34]
Configuration:

```
'pdf' => [
        'class' => Pdf::classname(),
        'format' => Pdf::FORMAT_LETTER,
        'orientation' => Pdf::ORIENT_LANDSCAPE,
        'destination' => Pdf::DEST_BROWSER,
        'cssFile' => '@webroot/css/document.css',
        'marginTop' => 10,
],
```

Controller:

```
$pdf = Yii::$app->pdf;
$pdf->methods = ['SetFooter' => ['{PAGENO}']];
$pdf->content = $this->renderpartial('_tracker', [
       'year' => $year,
       'customer' => $models['customer'],
       'totals' => $models['totals']
]);
$pdf->filename = 'Tracker.pdf';

return Yii::$app->pdf->render();
```

The script above works well in desktop browsers (Chrome, Opera, Firefox, IE) and mobile browsers (Firefox, Opera). However, it showed an error when I opened the page using Chrome mobile (Android):
`Cannot display PDF (index.php is of invalid format)`

Could this be related to Google Drive PDF Viewer issue (https://productforums.google.com/forum/#!topic/drive/xkkVSoLSIxo;context-place=topicsearchin/drive/category$3Adrive-mobile-app%7Csort:relevance%7Cspell:false)? I opened the mPDF demo page (http://demos.krajee.com/site/mpdf#demo) and it was displayed properly on Chrome mobile. Did I make a mistake in the configuration?

Yii: 2.0.9
Chrome mobile: 52.0.2743.98

**Comment by mile-janev** [comment]
@re1naldo How you fix this? I have the same issue.

**Comment by re1naldo** [comment]
@mile-janev Couldn't fix this. I had to install external PDF viewer in order to display PDF correctly.

**Comment by kartik-v** [comment]
You need to check and control this via your PDF Content and Characters that you render, which should be understood by all PDF viewers.

For example, [the PDF on the demo page](http://demos.krajee.com/site/mpdf#demo) uses simple formatting and normal roman characters and content formatting, that will be understood by most PDF viewers.
