### ISSUE TITLE
Deprecated constructor for mpdf on php version 7.0.4

### ISSUE THREAD

**Issue by edwardkads** [kartik-v/yii2-mpdf#35]
Getting an error for: "Methods with the same name as their constructor class will not be constructors in a future version of PHP"

**Comment by CyanoFresh** [comment]
Same

**Comment by kartik-v** [comment]
Please report this in the [mpdf repository](https://github.com/mpdf/mpdf)... this may need enhancements to be done to the mpdf library for PHP 7.
