### ISSUE TITLE
Illegal string offset 'ID' on PHP 7.1

### ISSUE THREAD

**Issue by adrianpaiva1** [kartik-v/yii2-mpdf#37]
I'm getting Illegal string offset 'ID' after upgrading to PHP 7.1 is there a workaround for this?

vendor/mpdf/mpdf/classes/cssmgr.php

**Comment by adrianpaiva1** [comment]
1293129412951296129712981299130013011302130313041305130613071308130913101311    {
        $p = array();
        $zp = array();
 
        $classes = array();
        if (isset($attr['CLASS'])) {
            $classes = preg_split('/\s+/', $attr['CLASS']);
        }
        if (!isset($attr['ID'])) {
            $attr['ID'] = '';
        }
        // mPDF 6
        $shortlang = '';
        if (!isset($attr['LANG'])) {
            $attr['LANG'] = '';
        } else {
            $attr['LANG'] = strtolower($attr['LANG']);
            if (strlen($attr['LANG']) == 5) {
                $shortlang = substr($attr['LANG'], 0, 2);

**Comment by adrianpaiva1** [comment]
I've managed to resolve this issue on PHP 7.1 by adding "$attr = is_array($attr) ? $attr : [];" to the cssmgr.php on line 1296.

Could you possibly release a new update with this included?

**Comment by ItsReddi** [comment]
@kartik-v same here

**Comment by massicode** [comment]
Resolved here https://github.com/mpdf/mpdf/issues/278
just add 
"mpdf/mpdf": "6.1.3",

in composer.json

**Comment by StalkAlex** [comment]
There is an issue about adding support for 7th version https://github.com/kartik-v/yii2-mpdf/issues/45. 
Officially mPdf v6 will not provide support for php 7.0+, so there is one way to use only 7th version. 
You can have a look at my fork https://github.com/StalkAlex/yii2-mpdf/tree/php71 where I resolved this problem by updating mPdf to 7th version.

**Comment by jeffersonor900** [comment]
StalkAlex Erro 404

**Comment by StalkAlex** [comment]
@jeffersonor900 sorry, I dropped my fork as everything has been working in Kartik's repository. Please use last version, you'll need to change only package version. 
```json
"kartik-v/yii2-mpdf": "dev-master",
```

**Comment by jeffersonor900** [comment]
adrianpaiva1 tengo el mismo problema...
