### ISSUE TITLE
I can't install this extension

### ISSUE THREAD

**Issue by jose1894** [kartik-v/yii2-mpdf#39]
Hi,

I'm a newbie with Yii, and I'm beginning a project with that framework by a petition.

I need to generate some reports in PDF, and I try to install this extension with composer using this code:

php composer.phar require kartik-v/yii2-mpdf "dev-master"

But when composer starts the download, gives a message error, like that:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package kartik-v/yii2-mpdf could not be found in any version, there may be a typo in the package name.

Could you give me some help with that? 

Thanks,

PD: Sorry for my bad English

**Comment by linslin** [comment]
The developer of this repositoryr does not drive GitFlow. So there is no dev branch here. In that way composer does not find a dev branch, which you are focusing in our installation. 

Try
  `"kartik-v/yii2-mpdf": "1.0.0"`

You will find more basic information about using composer and package versions here: https://getcomposer.org/doc/articles/versions.md
