### ISSUE TITLE
Add ability to disable repeating table header row on new page

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-mpdf#44]
The mpdf default always repating table header on a new page, but sometimes we need to disable this in [mpdf documentation](https://mpdf.github.io/tables/tables.html#repeating-table-header-row-on-new-page) this feature should be affected, but in fact is not

I try to use 
```php
'tableOptions'=>[
   'class' => 'table table-bordered table-condensed',
   'repeat_header' => 0, // or 1
],
```
Still not affected

I think this options is can enable from grid/export(mpdf) options

**Comment by kartik-v** [comment]
You need to configure it in mPdf options (using mPdf component config). You are wrongly setting this in `GridView::tableOptions`.

**Comment by adiramardiani** [comment]
I try in grid export config, still not affected
```php
'exportConfig' => [
    GridView::HTML => true,
    GridView::EXCEL => true,
    GridView::PDF => [
        'config' => [
            'options' => [
                'title' => $this->title,
                'repeat_header' => 0,
            ],
            'methods' => [ 
                'SetHeader'=>[date('d/m/Y H:i:s').' - '.Yii::$app->user->identity->name], 
                'SetFooter'=>['[ {PAGENO} ]'],
            ]
        ]
    ]
],
```

Can you able to give an example configuration ?

**Comment by adiramardiani** [comment]
Have a working example for this ? please :)
