### ISSUE TITLE
Update to 7th version.

### ISSUE THREAD

**Issue by StalkAlex** [kartik-v/yii2-mpdf#45]
Could you consider update to 7th version? Mpdfs maintainers aren't going to support 6th version for php 7.1. https://github.com/mpdf/mpdf/issues/288

**Comment by StalkAlex** [comment]
I did a bit work. Basic functionality is working now in PHP 7.1 https://github.com/StalkAlex/yii2-mpdf/tree/php71. But ofc rest code should be checked properly.

**Comment by kartik-v** [comment]
Refer updated release v1.0.1.

**Comment by StalkAlex** [comment]
I've seen your changes but don't understand a bit what's going on. You're still using old mpdf, why have you closed this issue? Please explain.

**Comment by kartik-v** [comment]
This was more to do with changing dependency from `kartik-v/mpdf` to `mpdf/mpdf` repo (where enhancements for newer PHP releases are being done)

As to using the other unstable versions of `mpdf/mpdf`... have not tested it - so restricting it to the latest stable releases. 

Parallely have reopened the issue for any other suggestions for PHP 7.1.

**Comment by StalkAlex** [comment]
Ok. Thank you! I added a few changes to use last version,  so it works as previous without any problem, of course there is a chance for mPdf maintainers to change something due to development, but I don't think they will change main function interface again.

**Comment by StalkAlex** [comment]
There is mPdf 7.0.0 beta has been released. So I guess it's good point to add support to your library too. Maybe as another version or branch. You could use my fork with changed code mentioned above. I adopted your library for the last mPdf version.  It has been tested and works quite well for awhile already.

**Comment by StalkAlex** [comment]
It's not a fix. You just rised version. mPdf 7's api changed, so current code of your library will not work with new version of mPdf.

**Comment by kartik-v** [comment]
Not sure I understand ... You can cross check with demos... The latest version of mpdf api
