### ISSUE TITLE
Unable to get Water mark image

### ISSUE THREAD

**Issue by tejrajs** [kartik-v/yii2-mpdf#46]
who to get water mark Image?
$pdf->getApi()->SetWatermarkImage('image link');

**Comment by artempetrovjava** [comment]
The same problem

**Comment by seisvalt** [comment]
U

> who to get water mark Image?
> $pdf->getApi()->SetWatermarkImage('image link');


a little late,:

$mpdf = $pdf->getApi();
$mpdf->SetWatermarkImage('img/theimage.png',0.3, '',[10,150]);
$mpdf->showWatermarkImage = true;
return $pdf->render();

More info params

[https://mpdf.github.io/reference/mpdf-functions/setwatermarkimage.html](https://mpdf.github.io/reference/mpdf-functions/setwatermarkimage.html)
