### ISSUE TITLE
QR code in PDF

### ISSUE THREAD

**Issue by DBX12** [kartik-v/yii2-mpdf#50]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-mpdf.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/mpdf).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
See below

## Expected behavior and actual behavior

When I follow those steps, I see...
a "missing image" icon in the PDF

I was expecting...
the QR code

#### Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-mpdf version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [X] The bug happens consistently across all tested browsers (only Firefox tested)
- [ ] This bug happens when using yii2-mpdf without other plugins.

I'm using your PDF extension and the QR-Code extension from [2amigos](https://github.com/2amigos/yii2-qrcode-helper). The issue I run into is the following:
In my view `_pdf` I "include" the QR code by `<img src="<?= Url::to(['route/qrcode','text'=>$model->qr_code_content]) ?>" />`
In my Controller I have this function
```php
public function actionQrcode($text){
    Yii::$app->response->format = Response::FORMAT_RAW;
    Yii::$app->response->headers->set('Content-Type','image/png');
    return QrCode::png($text)
}
```

The Controller renders the view in the `actionPdf`

```php
public function actionPdf($id) {
        $model = $this->findModel($id);
        #return $this->renderPartial('_pdf', ['model' => $model]);
        $content = $this->renderPartial('_pdf', ['model' => $model]);
        $pdf = new Pdf([
            'content' => $content,
            'filename' => 'Ticket_' . $model->id . '.pdf',
            'options' => [
                'title' => 'Your ticket as '
            ],
            'cssFile' => '@webroot/css/pdf.css'
        ]);
        $pdf->render();
    }
```

In the PDF the QR code is displayed as "missing image" icon, if I uncomment the third line (`return $this->renderPartial(...` the page renders as normal HTML and the QR code is displayed correctly.
I will also open an issue for the mpdf extension.  Please look up the issue together with 2amigos, thx
See also my comment on the [issue](https://github.com/2amigos/yii2-qrcode-helper/issues/11)  in the 2amigos/yii2-qrcode-helper repo

**Comment by kartik-v** [comment]
You may need to check how image embedding in PDF output is handled by mPDF library. Note that PDF output and HTML output handling are entirely different.

Refer  [mPDF library docs for image processing](https://mpdf.github.io/what-else-can-i-do/images.html).

**Comment by dwisuseno** [comment]
I get same problem here. how to solve it? @kartik-v

**Comment by qomarsuroradi** [comment]
i get same problem..

**Comment by kartik-v** [comment]
Folks as i mentioned you need to configure the mPDF extension library to achieve your needs. This issue is not related to this extension as it just wraps the mPDF library for use in yii2. If you have suggestions to.improve please open a new issue.
