### ISSUE TITLE
update to allow use of Mpdf 7.0 and PHP 7.1.

### ISSUE THREAD

**Issue by BlaDrzz** [kartik-v/yii2-mpdf#51]
## Steps to reproduce the issue

1. use a php 7.1 environment
2. attempt to use the kartik-v/yii2-mpdf library

## Expected behavior and actual behavior

When I follow those steps, I see a whole bunch of errors because mpdf 6 does not support PHP 7.1.X and yii-mpdf does not support a higher version of mpdf. It works fine if I just use the mpdf library to export simple pages but when used in combination of other elements (such as the GridView widget it throws an error.

`Invalid Configuration – yii\base\InvalidConfigException

The class '\kartik\mpdf\Pdf' was not found and is required for PDF export functionality. To include PDF export, follow the install steps below. If you do not need PDF export functionality, do not include 'PDF' as a format in the 'export' property. You can otherwise set 'export' to 'false' to disable all export functionality.

Please ensure you have installed the 'yii2-mpdf' extension. To install, you can run this console command from your application root:

php composer.phar require kartik-v/yii2-mpdf: "@dev"`

Your wrapper should be updated to support the new PHP versions as well as the latest Mpdf version. Please update.

## Environment

Xampp, PHP 7.1.1

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: irrelevant
- yii2-mpdf version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-mpdf without other plugins.

**Comment by kartik-v** [comment]
mpdf 7.0 is in beta and not in stable release yet.

**Comment by BlaDrzz** [comment]
It's a lot more stable than using PHP 7.1 with yii2-mpdf..

So what is the solution for people who are stuck using PHP 7+?

**Comment by kartik-v** [comment]
> It's a lot more stable than using PHP 7.1 with yii2-mpdf..

- Is there a test of using mPDF 7.0 BETA on all versions of PHP 5.x, 6.x, 7.x and have you tested it?

Based on above will need to figure out release and dependencies here... as it cannot be just addressed in context of PHP 7.1

**Comment by BlaDrzz** [comment]
I removed the yii2-mpdf package, updated mpdf to 7.0.0-beta2, then changed my code and I am running it perfectly on my test xampp (PHP 7.1.1) and on my production server (PHP 7.1.3).

**Comment by kartik-v** [comment]
Still I am not sure of the other versions of PHP < 7.x...

give me some time will need to create another release specific for 7.1 -

**Comment by BlaDrzz** [comment]
The only issue I encounter now is that the yii2-gridview can not export to PDF, but that is a different github project. Fixed it by just change the export options to not include PDF since it still uses the yii2-mpdf. If you need any code or need anything tested on PHP7 let me know I'd be willing to help out.

**Comment by mhoogstraten** [comment]
Any update on this?

**Comment by StalkAlex** [comment]
I did some work already adopting last version of PHP and mPdf. There's already opened issue on this problem https://github.com/kartik-v/yii2-mpdf/issues/45#issuecomment-291846586. @mhoogstraten you could give a try to my forked version

**Comment by StalkAlex** [comment]
Same as here https://github.com/kartik-v/yii2-mpdf/issues/45#issuecomment-309336095

**Comment by juanisorondo** [comment]
@kartik-v anything I can do to help speed up yii2-mpdf with mPDF 7.0?

**Comment by kartik-v** [comment]
@juanisorondo I released 1.0.2 tag... can you check and update if anything... thanks
