### ISSUE TITLE
Remove border bottom header

### ISSUE THREAD

**Issue by edsonrbispo** [kartik-v/yii2-mpdf#53]
How to remove the boder-bottom of the header

**Comment by dieruckus** [comment]
Try this:

 $pdf = new Pdf([ .....
     'options' => [               
                'defaultheaderline' => 0,  //for header
                 'defaulfooterline' => 0  //for footer
            ],
]);

**Comment by microinginer** [comment]
> ```
>  $pdf = new Pdf([ .....
>      'options' => [               
>                 'defaultheaderline' => 0,  //for header
>                  'defaulfooterline' => 0  //for footer
>             ],
> ]);
> ```
```php
 $pdf = new Pdf([ .....
     'options' => [               
                'defaultheaderline' => 0,  //for header
                 'defaultfooterline' => 0  //for footer
            ],
]);
```
replace defaulfooterline to defaul**t**footerline
