### ISSUE TITLE
Font size not increasing.

### ISSUE THREAD

**Issue by raksrivastava** [kartik-v/yii2-mpdf#54]
When i am generating pdf, font style is too small, we can not read in that font size. My code is below. 
$pdf = new Pdf([
                'mode' => Pdf::MODE_CORE,
                'format' => Pdf::FORMAT_A4,
                'orientation' => Pdf::ORIENT_PORTRAIT,
                'destination' => Pdf::DEST_BROWSER,
               // 'cssFile' => '@web/css/kv-mpdf-bootstrap.min.css',
               // 'cssInline' => '.table{font-size:28px}',
            ]);
          
            $mpdf = $pdf->api;
 $mpdf->WriteHtml($content);
return $mpdf->Output('test.pdf', 'D');

**Comment by raksrivastava** [comment]
It is working now by adding below lines.
$mpdf->keep_table_proportions = false;
 $mpdf->SetDefaultFontSize(9);

**Comment by githubyyf** [comment]
I need your help raksrivastava and kartik-v .

I have the same problem as you.
I set like  raksrivastava,but this is a situation that occurs  When the content is too much,font style is too small, we can not read in that font size.  My code is below.
$pdf = new  Pdf([
            'mode'        => Pdf::MODE_UTF8, // leaner size using standard fonts
            'cssFile'     => Yii::$app->params['System']['exportCssDir'] . 'site.css', //css file
            'content'     => $content,
            'filename'    => $saveFile,
            'destination' => 'F',
            'options'     => [
                'title'                  => 'company',
                'subject'                => 'company',
                'autoLangToFont'         => true,
                'autoScriptToLang'       => true,
                'autoVietnamese'         => true,
                'autoArabic'             => true,
                'keep_table_proportions' => false,
            ],
            'methods'     => [
                'SetHeader' => [$typeName . '信息||日期: ' . date('Y-m-d', time())],
                'SetFooter' => ['|第 {PAGENO} 页，共 {nb} 页|'],
            ],
        ]);

        $pdf->defaultFontSize = 20;
        $pdf->render();
        

My css file set 
.td_width{
    width: 250px;
    font-size: 14px;
}
When the content is too much,font style is too small, we can not read in that font size,like this:
![pdf](https://user-images.githubusercontent.com/21100974/28197989-47f67d92-688d-11e7-944a-28dd163cab51.png)


my .html file 

![html](https://user-images.githubusercontent.com/21100974/28198038-a632a11a-688d-11e7-9311-2d9e5694d858.png)

Thank you very much 

@raksrivastava  @kartik-v
