### ISSUE TITLE
constant(): Couldn't find constant _MPDF_TEMP_PATH

### ISSUE THREAD

**Issue by hagenr** [kartik-v/yii2-mpdf#59]
Recent changes in dev-master resulted in an error during definePath()

when the prop is not defined constant() throws

```
$propDir = constant($prop);
 if (defined($prop) && is_writable($propDir)) {

maybe better
 if (defined($prop) && is_writable(constant($prop))) {
```

**Comment by hagenr** [comment]
if (defined($prop) && is_writable(constant($prop))) {

fixed it.

**Comment by kartik-v** [comment]
Will update on this...
