### ISSUE TITLE
Class 'mPDF' not found

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-mpdf#6]
I just installed this extension via composer and got this error when trying to use it:

```
PHP Fatal Error – yii\base\ErrorException: Class 'mPDF' not found
in /opt/lampp/htdocs/basic/vendor/kartik-v/yii2-mpdf/Pdf.php at line 201
```

yii2-mpdf & mpdf are already in /vendor/kartik-v directory and yii2-mpdf has been added to extensions.php. Am I missing something here?

**Comment by re1naldo** [comment]
I have refreshed the packages but still got this error. Under kartik-v directory, there should be mpdf and yii2-mpdf directories, right? When you called `use \mPDF` in  `kartik-v/yii2-mpdf/Pdf.php`, does it refer to `kartik-v/mpdf/mpdf.php`?

**Comment by kartik-v** [comment]
Yes.

**Comment by re1naldo** [comment]
Not sure what the problem is. The installation doesn't seem to be corrupt and I can see `mpdf.php` file under `kartik-v/mpdf/` directory, but I still receive `Class 'mPDF' not found` error. Is there anything else to be checked to debug this problem?
