### ISSUE TITLE
Unicode rendering issue

### ISSUE THREAD

**Issue by induwarabas** [kartik-v/yii2-mpdf#63]
I am trying to create a pdf with unicode characters. But it render squares instead of unicode characters. Is there any additional configuration for unicode rendering?
I tried different characters like আসসালামু আলাইকুম નમસ્તે നമസ്കാരം नमस्ते வணக்கம்!මාගේ අංකය: 02/05/F/01/06.
All of them are rendered to squares.

**Comment by kartik-v** [comment]
Set `mode` property within the `Pdf` component to `Pdf::MODE_UTF8`. You can read more about setting fonts in the Mpdf docs.

**Comment by induwarabas** [comment]
Thanks!
But simply changing the MODE did not work. I did it by changing the font using html styles. Also I tried to use Sinhala language. It did not processed properly. As an example if I typed ග්‍රාමිය, it shows ග්රාමිය. Actually this happens when there is a unicode processing issue. Anyway, I did it by using sinhala font, instead of using unicode font.
