### ISSUE TITLE
Not able to use css Zoom Content in Mpdf

### ISSUE THREAD

**Issue by Praveenom3** [kartik-v/yii2-mpdf#64]
Mpdf is not able to zoom content. I am trying to use zoom : 0.8 in mpdf div but it is not working. Basically i need to make the div elements smaller and fit in single page.

**Comment by finwe** [comment]
Zoom is not a supported CSS property in mPDF. 

https://mpdf.github.io/css-stylesheets/supported-css.html

**Comment by kartik-v** [comment]
Exactly as @finwe pointed out... mpdf supports mostly CSS 2 specifications.
