### ISSUE TITLE
php 7.1.*

### ISSUE THREAD

**Issue by hooman-pro** [kartik-v/yii2-mpdf#67]
I try to install with composer but becuse my xampp have php 7.1 it throw error

**Comment by NestorAcevedo** [comment]
Is related to https://github.com/mpdf/mpdf/issues/443

Is a problem with the real mPDF

**Comment by EvgenyVetrov** [comment]
same problem. Need to upgrade mpdf up to v7.0.1 in widget...

**Comment by Geoffry304** [comment]
@kartik-v  Plz update mpdf to version 7.0.0 and add new release normally this will fix it

**Comment by kartik-v** [comment]
This is already done sometime back.
