### ISSUE TITLE
Headers already sent

### ISSUE THREAD

**Issue by laziz-karimov** [kartik-v/yii2-mpdf#70]
When using `'destination' => Pdf::DEST_DOWNLOAD` I am getting warning 
`Headers already sent in /vendor/mpdf/mpdf/src/Mpdf.php on line 9342.`
Any one has an idea why?

**Comment by xtinem** [comment]
Experiencing the same thing. Need to refresh the page so it will go through the pdf file. 

![image](https://user-images.githubusercontent.com/13326113/34567750-7b94fae4-f19e-11e7-9d91-2385f5a24f08.png)

**Comment by kartik-v** [comment]
Check release v1.0.4.
