### ISSUE TITLE
Render error on dataprovider sort disabled

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-mpdf#71]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-mpdf.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/mpdf).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set sort to false on data provider: `$dataProvider->setSort(false);`
2. Get HTML raw content on variable to use with PDF
3. Configure new Pdf object  `$pdf = new Pdf([...]);` and return PDF output 

## Expected behavior and actual behavior

When I follow those steps, I see...
A bad render: 

> %PDF-1.4 %���� 3 0 obj <> (...)

It is presents only with AdminLTE and in only one view. With default theme (Yii2 predefined view), all views are rendered normally.

I was expecting...
Render of view just like HTML with disabled table header sort.

## Environment
PHP 7.1.12
#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-mpdf version: dev-master 67980ab

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-mpdf without other plugins.

**Comment by diego-betto** [comment]
try setting 
'mode' => Pdf::MODE_BLANK
