### ISSUE TITLE
Column is getting pushed to the next line.

### ISSUE THREAD

**Issue by bluetechy** [kartik-v/yii2-mpdf#8]
I tried using this project's custom bootstrap file to see if this would resolve the same problem documented by the following two link where the col-xs-# class moves to the next line:

* http://stackoverflow.com/questions/27691475/mpdf-and-bootstrap-column-on-next-line
* https://groups.google.com/forum/#!topic/twitter-bootstrap-stackoverflow/

Got any suggestions on how to resolve this issue?

**Comment by kartik-v** [comment]
Not sure about the above - but as a rule... mPDF works with CSS2 specs and does not work with new CSS3 specs (unless those features are CSS2 compliant). You would need to use markup that is supported in CSS2.
