### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by winkersco** [kartik-v/yii2-mpdf#82]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-mpdf.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/mpdf).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. I write this code in controller:
```php

public function actionTest($id)
{
    $model = $this->findModel($id);
    $content = $this->renderPartial('view', [
        'model' => $model,
    ]);
    $pdf = new Pdf([
        'mode' => Pdf::MODE_UTF8,
        'content' => $content,
    ]);
    return $pdf->render();
}

```
2. and then send request to this action.

## Expected behavior and actual behavior

When I follow those steps, I see that a `yii\base\ErrorException` occurs.

![image](https://user-images.githubusercontent.com/24722498/43601022-765a8582-96a1-11e8-9c8d-a925ebc12139.png)
   

I was expecting to render a PDF from view.

## Environment

Apache/2.4.26 (Unix) OpenSSL/1.0.2l PHP/7.1.7 mod_perl/2.0.8-dev Perl/v5.16.3
Yii Framework/2.0.15.1

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [] Internet Explorer
- [] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-mpdf version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-mpdf without other plugins.

**Comment by winkersco** [comment]
@kartik-v

**Comment by ricar2ce** [comment]
Hello @winkersco , greetings, did you find the solution for this problem?
I am in the same situation
