### ISSUE TITLE
file_put_contents(.../mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by kdjonua** [kartik-v/yii2-mpdf#9]
I'm using mPDF inmy action like this:
```php
$pdf = new Pdf([
                    'mode' => Pdf::MODE_UTF8,
                    'format' => Pdf::FORMAT_A4,
                    'orientation' => Pdf::ORIENT_PORTRAIT,
                    'destination' => Pdf::DEST_BROWSER,
                    'content' => $output,
                    'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
                    'cssInline' => '.kv-heading-1{font-size:18px}',
                    'options' => ['title' => 'My report ' . date("Y/m/d", time())],
                    'methods' => [
                        'SetHeader'=>['My report ' . date("Y/m/d", time())],
                        'SetFooter'=>['{PAGENO}'],
                    ]
                ]);

                return $pdf->render();
```
and I receive the exception:
```quote
file_put_contents(/home/iam/git/superproject/application/vendor/kartik-v/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: Permission denied
```
How can I solve this trouble?

**Comment by gwelr** [comment]
it probably means your web server does not have write access to ttfontdata/ folder or that dejavusanscondensed.GSUBGPOStables.dat already exists but could not be written by the web server. Did you manage to fix the issue on your side?

**Comment by Sentoki** [comment]
A have same problem in Symfony2. mpdf located in vendor, it's ok try write to vendor directory?

**Comment by kartik-v** [comment]
You may want to check permissions and also look out for help on mpdf forums.

For example [see if this solution helps](http://www.mpdf1.com/forum/discussion/460/internal-server-error-with-mpdf-5-0/p1)

**Comment by Sentoki** [comment]
Solve this problem by: define('_MPDF_TTFONTDATAPATH',$temp_dir); before creating instance of mPDF.
$temp_dir is dir out of vendor. All work fine now.

**Comment by kartik-v** [comment]
Thanks for the feedback. I may provide a configuration option for this in the component as well.

**Comment by kartik-v** [comment]
Will be resolved via #12.

Closing this.

**Comment by sheetal4123** [comment]
file_put_contents(/var/www/cluewiz/vendor/mpdf/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: No such file or directory

Getting this error

**Comment by anton-github** [comment]
I started getting the same error, and I think I finally figured out.
After kartik-v changed $pdfLibraryPath property from '@vendor/kartik-v/mpdf' to '@vendor/mpdf/mpdf' (https://github.com/kartik-v/yii2-export/commit/8b60570fb3f541c2fac8ea4ea8e221d6a28e8750#diff-76ff5c7d38933d45f929b811c29f3b62R444) constant _MPDF_TTFONTDATAPATH now gets value from mpdf/mpdf again and tries to write to the vendor (before that commit _MPDF_TTFONTDATAPATH overrides to Yii::getAlias('@runtime/mpdf') during kartik-v/mpdf initialization)

**Comment by asmythe** [comment]
Ran into this same issue. Did the following before instancing mPDF and it worked.

			define('_MPDF_TTFONTDATAPATH',Yii::getAlias('@runtime/mpdf'));

**Comment by kartik-v** [comment]
This is already taken care of in the Pdf component [in this place](https://github.com/kartik-v/yii2-mpdf/blob/master/Pdf.php#L199) ... not sure you would need to do that...

**Comment by anton-github** [comment]
Hi, kartik-v, check please my comment above. I could be wrong, but kartik-v/mpdf component did not initializing at all since your commit (https://github.com/kartik-v/yii2-export/commit/8b60570fb3f541c2fac8ea4ea8e221d6a28e8750#diff-76ff5c7d38933d45f929b811c29f3b62R444)

**Comment by kartik-v** [comment]
@anton-github the component does initialize fine as seen on the [demos page](http://demos.krajee.com/mpdf#demo) and it should use the logic I mentioned above to create the `mpdf` directory in your app's `runtime` folder. 

The commit you mentioned above has a repo change for mpdf and you need to ensure that the new extension with its dependencies (including the mpdf repo) are installed fine... and you do not have two different mpdf libraries.

**Comment by silkisethi** [comment]
file_put_contents(E:/websites/inwork_husnes/vendor/mpdf/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: Permission denied

Can anyone help me?

**Comment by gautam-patadiya** [comment]
I faces same problem :( I resolved to create tamp folder with permission 777 and its working :)....

**Comment by zmarket** [comment]
I solved by changing the _MPDF_TTFONTDATAPATH path to Linux temp directory 
 define('_MPDF_TTFONTDATAPATH', sys_get_temp_dir()."/");

**Comment by kartik-v** [comment]
If you wish to set your own temporary location set the `Pdf::tempPath` property to a valid temporary directory and the above should be automatically taken care of.
