### ISSUE TITLE
Not getting installed via composer. PHP version 7.3.7

### ISSUE THREAD

**Issue by araviaravi** [kartik-v/yii2-mpdf#96]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-mpdf.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/mpdf).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [X] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install PHP 7.3.7
2. Run composer require kartik-v/yii2-mpdf "dev-master" in root of Yii2 project directory
3. You will get error 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mpdf/mpdf v7.0.3 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.7) does not satisfy
that requirement.
    - mpdf/mpdf v7.0.3 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.7) does not satisfy
that requirement.
    - mpdf/mpdf v7.0.3 requires php ^5.6 || ~7.0.0 || ~7.1.0 || ~7.2.0 -> your PHP version (7.3.7) does not satisfy
that requirement.
    - Installation request for mpdf/mpdf (locked at v7.0.3) -> satisfiable by mpdf/mpdf[v7.0.3].

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-mpdf version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-mpdf without other plugins.

**Comment by anburocky3** [comment]
Any update on this issue? Why is it closed without solution?

**Comment by aravindSRM-India** [comment]
Hi anburocky3,

I have updated both composer and fxp/composer-asset-plugin.This solved my issue. 

Looks like bot auto closed the ticket.
