### ISSUE TITLE
Can't install on Latest PHP 7.3.11.

### ISSUE THREAD

**Issue by anburocky3** [kartik-v/yii2-mpdf#99]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-mpdf.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/mpdf).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-mpdf version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/mpdf)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-mpdf without other plugins.

**Comment by anburocky3** [comment]
No reply from maintainers... Is th project dead?

**Comment by kasoft** [comment]
Check your composer Settings to be sure to Install Verion 1.0.5 (!)
With mpdf Version 7.1.0 you're fine with PHP 7.3
 
- Updating mpdf/mpdf (v6.1.3 => v7.1.9): Downloading (100%)         
- Updating kartik-v/yii2-mpdf (v1.0.1 => v1.0.5):  Checking out 908c8d15ae

**Comment by kartik-v** [comment]
The mpdf library dependency is:

```
"mpdf/mpdf": "~8.0
```

which should work with PHP 7.x and later. Check your composer settings and dependencies.

**Comment by ashrafakl** [comment]
@kartik-v the mpdf in the latest release (1.05) setting is : 

> "mpdf/mpdf": "~7.0

**Comment by kartik-v** [comment]
It works with PHP 7.x without issues - can you retry updating via composer to the latest version v1.0.6. The version 1.0.6 includes support exclusively for mpdf v8.0 and up.
